### ISSUE TITLE
Implement frame packing to increase display frame rate from 120 Hz to 240 Hz

### ISSUE THREAD

**Issue by hjmh** [JaneliaSciComp/janelia-unity-toolkit#34] opened 2020-08-28 16:42 UTC
It seems that for now running 4 projectors at 240 Hz does not work (projectors don't display images), but everything is stable at 120 Hz.

We could display consecutive VR frames at 240 Hz nonetheless, by showing different frames for the three different color channels (frame packing, as it was used in FlyoVeR). Packing a different frame into each color channel only makes sense if the color channels are shown for equal periods of time. In the projectors I use that is not the case, but two channels are shown together for roughly the same amount of time as the third one, so we could pack the same frame into the two short channels (showing it twice) and then show a fresh frame in the next long frame. That strategy would get us from 120 Hz to 240 Hz.

**Comment by hubbardp** [comment] 2020-09-02 10:00
I wonder if the problem is related to HMDI.  In my experience driving an Acer XF250Q 240 Hz monitor from my laptop's NVIDIA 2080 RTX card, I was not able to get 240 Hz from the card's HDMI output but I was able to get it from the card's mini-DP output .  I wonder if a better HDMI cable would help.

**Comment by hubbardp** [comment] 2023-05-23 17:48
I added frame packing a while back with this pull request: https://github.com/JaneliaSciComp/janelia-unity-toolkit/pull/133
So I am going to close this issue.

**Closed by hubbardp** 2023-05-23 17:48 UTC
