### ISSUE TITLE
NiDaqMx issue

### ISSUE THREAD

**Issue by fbencive** [JaneliaSciComp/janelia-unity-toolkit#137] opened 2023-04-28 11:56 UTC
Hi all,
I have an issue with the Ni-da-mx package.
I have installed the NI-DAQmx drivers (and indeed the nicaiu.dll is in C:\Windows\System32). In the ExampleUsingNiDaqMx.cs script, I see warnings at lines 42-48-49-50 such as "Property or indexer 'NiDaqMx.InputParams.ChannelNames' cannot be assigned to -- it is read only". What might be the issue?

Thank you!

Federica

**Comment by fbencive** [comment] 2023-04-28 16:22
Oh I see! Well I just tested the nidaq and it works smoothly with the changes I made. Thank you for the help!

**Comment by hubbardp** [comment] 2023-05-23 17:45
Although I could not reproduce the error with older versions of the Unity editor, I went ahead and switched from the newer "=>" syntax (expression-bodied members) to the older "return" syntax, because the older syntax seems to work fine for me, too.  I committed the change, and I am closing this item.  Let me know if there are any further problems!

**Closed by hubbardp** 2023-05-23 17:45 UTC
